spring:
  application:
    name: java-large-file-uploader-demo
  http:
    multipart:
      enabled: true
      max-file-size: 20000MB
      max-request-size: 100MB
      resolve-lazily: true
      file-size-threshold: 0
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
    check-template: false
    enabled: true
    template-resolver-order: 0
server:
  port: 9000
  tomcat:
    basedir: target/tomcat
    accesslog:
      enabled: true
      directory: logs
    max-threads: 200
    uri-encoding: UTF-8
  error:
    path: /error
logging:
  level:
    root: info
    com.am: info
    org.apache: warn
    org.hibernate: warn
    org.springframework: warn
  file: target/logs/log.txt